### ISSUE TITLE
DeWeb doesn't support sub-domains (problem on acheta provider buildnet)

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/Deweb-Providers#8]
```
 title: Acheta bot MASSA DeWEB Provider (Buildnet)
  url: https://dev.massa-deweb.xyz/
  desc: Acheta team MASSA DeWEB provider
  owner: Acheta Team
  network: buildnet
  contact:
    telegram: https://t.me/xk003
``` 

acheta subdomain doesn't work as intended 
--> https://docs.dev.massa-deweb.xyz/ should work but it does not display the docs
